name: hello-dubbo-service-api
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: rdc-snapshots
          settings-path: ${{ github.workspace }}
      - name: Build with Maven
        env:
          MAVEN_USER_NAME: ${{ secrets.MAVEN_USER_NAME }}
          MAVEN_USER_PASSWORD: ${{ secrets.MAVEN_USER_PASSWORD }}
        run: |
          mv /usr/share/apache-maven-3.6.3/conf/settings.xml /usr/share/apache-maven-3.6.3/conf/settings.xml.bak
          cp maven-settings.xml /usr/share/apache-maven-3.6.3/conf/settings.xml
          mvn clean deploy -DskipTests